baseURL = "http://www.palaniraja.com/websitev2/"
languageCode = "en-us"
title = "Palani Raja"
theme = "whiteplain"
publishDir = "docs"

uglyURLs = true
canonifyURLs = true

[permalinks]
  projects = "/:year/:month/:title/"