baseURL = "http://www.palaniraja.com/websitev2/"
languageCode = "en-us"
title = "PR"
theme = "min"


publishDir = "docs"

# uglyURLs = true
canonifyURLs = true

[permalinks]
 projects = "/:year/:month/:title/"
 posts = "/:year/:month/:title/"


[[menu.main]]
  name = "Resume"
  weight = 4
  identifier = "resume"
  url = "/resume"


[[menu.main]]
  name = "Archives"
  weight = 3
  identifier = "archives"
  url = "/archives"

[[menu.main]]
  name = "About"
  weight = 2
  identifier = "about"
  url = "/about"

[[menu.main]]
  name = "rss"
  weight = 1
  identifier = "atom"
  url = "/index.xml"

[mediaTypes]
    [mediaTypes."application/atom"]
    suffixes = ["xml"]

    [outputFormats.Atom]
    mediaType = "application/atom"
    baseName = "index"
    isPlainText = false

[outputs]
    home = [ "HTML", "Atom" ]
