baseURL = "http://www.palaniraja.com/websitev2/"
languageCode = "en-us"
title = "PR"
theme = "min"

copyright = "&copy; 2018 palaniraja"


publishDir = "docs"

# uglyURLs = true
canonifyURLs = true

paginate = 20

RSSLink = true
summaryLength = 20

[permalinks]
 projects = "projects/:title/"
 posts = "/:year/:month/:title/"



[[menu.main]]
  name = "Projects"
  weight = 1
  identifier = "projects"
  url = "/projects"


# [[menu.main]]
#   name = "Archives"
#   weight = 2
#   identifier = "archives"
#   url = "/archives"


[[menu.main]]
  name = "Blog"
  weight = 3
  identifier = "blog"
  url = "/posts"


[[menu.main]]
  name = "Archive"
  weight = 4
  identifier = "archive"
  url = "/archives"

[[menu.main]]
  name = "About"
  weight = 5
  identifier = "about"
  url = "/about"

[[menu.footer]]
  name = "Archive"
  weight = 1
  identifier = "Archive"
  url = "/archives/"

[[menu.footer]]
  name = "Categories"
  weight = 2
  identifier = "categories"
  url = "/categories/"

[[menu.footer]]
  name = "Tags"
  weight = 2
  identifier = "tags"
  url = "/tags/"


[[menu.footer]]
  name = "About"
  weight = 4
  identifier = "about"
  url = "/about/"


# [mediaTypes]
#     [mediaTypes."application/atom"]
#     suffixes = ["xml"]
# 
#     [outputFormats.Atom]
#     mediaType = "application/atom"
#     baseName = "index"
#     isPlainText = false

# [outputs]
#   home = [ "HTML", "Atom" ]
