baseURL = "http://www.palaniraja.com/websitev2/"
languageCode = "en-us"
title = "PR"
theme = "min"
publishDir = "docs"

# uglyURLs = true
canonifyURLs = true

# [permalinks]
#  projects = "/:year/:month/:title/"

[[menu.main]]
  name = "Archives"
  weight = 3
  identifier = "archives"
  url = "/archives"

[[menu.main]]
  name = "rss"
  weight = 2
  identifier = "atom"
  url = "/index.xml"

[mediaTypes]
    [mediaTypes."application/atom"]
    suffixes = ["xml"]

    [outputFormats.Atom]
    mediaType = "application/atom"
    baseName = "index"
    isPlainText = false

[outputs]
    home = [ "HTML", "Atom" ]
