baseURL = "http://www.palaniraja.com/websitev2/"
languageCode = "en-us"
title = "Palani Raja"
theme = "whiteplain"
publishDir = "docs"

uglyURLs = true
canonifyURLs = true
toc = false

[permalinks]
  projects = "/:year/:month/:title/"

[[menu.main]]
  name = "Archives"
  weight = 3
  identifier = "archives"
  url = "/archives.html"

[mediaTypes]
    [mediaTypes."application/atom"]
    suffix = "xml"

    [outputFormats.Atom]
    mediaType = "application/atom"
    baseName = "index"
    isPlainText = false

[outputs]
    home = [ "HTML", "Atom" ]
